namespace SwitchBot.Models;

public enum StatusType
{
    Version,
    Battery,
    Temperature,
    Humidity,
    Power,
    DeviceMode,
    Calibrate,
    Group,
    Moving,
    SlidePosition,
    LockState,
    DoorState,
    MoveDetected,
    Brightness,
    OpenState,
    ColorTemperature,
    Voltage,
    Weight,
    ElectricityOfDay,
    ElectricCurrent,
    Color,
    WorkingStatus,
    OnlineStatus,
    NebulizationEfficiency,
    Auto,
    ChildLock,
    Sound,
    LackWater,
    Direction,
    LightLevel,
}